### ISSUE TITLE
Package crash when trying to load a stage channel in an non community server.

### ISSUE THREAD

**Issue by lonelil** [Androz2091/discord-backup#291]
If you try to load an backup with an stage channel to an server that does not have community enabled the package will crash

Error:

```
user_limit: int value should be less than or equal to 99.
    at RequestHandler.execute (/home/runner/test-backup/node_modules\discord.js\src\rest\RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/runner/test-backup/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async GuildChannelManager.create (home/runner/test-backup/node_modules/discord.js/src/managers/GuildChannelManager.js:142:18) {
  method: 'post',
  path: '/guilds/865831870347608065/channels',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: {
      name: 'Music',
      topic: undefined,
      type: 2,
      nsfw: undefined,
      bitrate: 64000,
      user_limit: 10000,
      parent_id: '878146091235819560',
      position: undefined,
      permission_overwrites: undefined,
      rate_limit_per_user: undefined
    },
    files: []
  }
}
```

**Comment by andrelucaas** [comment]
same problem here

**Comment by Positive2022** [comment]
I am experiencing same issue even in latest version. Is there any workaround for this?

**Comment by sw3do** [comment]
A major update is coming soon. However, due to some university-related issues, I’m currently unable to focus on it. A more detailed update will be provided as soon as possible. Thank you for your understanding.
