### ISSUE TITLE
Loading backup from file

### ISSUE THREAD

**Issue by robertcupisz** [Androz2091/discord-backup#30]
Hey, trying to load the attached test backup file
[684874311907016704.json.txt](https://github.com/Androz2091/discord-backup/files/4292636/684874311907016704.json.txt)
(added the txt extension for github to want to attach it)

```
(node:24652) UnhandledPromiseRejectionWarning: TypeError [INVALID_TYPE]: Supplied overwrites is not an Array or Collection of Permission Overwrites.
at CategoryChannel.overwritePermissions (/Users/robert/Desktop/DiscordBackupBot/node_modules/discord.js/src/structures/GuildChannel.js:208:9)
at Object.<anonymous> (/Users/robert/Desktop/DiscordBackupBot/node_modules/discord-backup/lib/master/util.js:181:71)
```

Tried an early out in case the array of permissions is empty to get rid of this exception, but the restore still fails - no text channels get restored.

(An unrelated issue, but might point out that there's something wrong with my setup: loading backup by id doesn't work either - the backup can't be found, even though listing the backups with list() shows the id)

**Comment by Androz2091** [comment]
Hello, I tried to load your backup with my own bot and it worked (text channels and permissions restored):

![Capture d’écran 2020-03-05 à 17 16 17](https://user-images.githubusercontent.com/42497995/76001260-1e892100-5f05-11ea-84ab-e30cbd6545f0.png)

__Versions__:
* discord backup 2.1.12
* discord.js master branch (commit: `21d37ed0cc71b227be0feadc4ffbcd522ca4f00e`)

Are you using the same versions?

**Comment by robertcupisz** [comment]
Hey, thanks for the reply
discord backup 2.1.12
discord.js 12.0.1 (two commits behind head, don't look related)

Maybe there's a difference in how the bot is configured or its permissions? Or how it calls load()?

Could you maybe post your bot code, please?

**Comment by Androz2091** [comment]
Here is the code I use for my tests:

```js
// Load modules
const Discord = require("discord.js"),
backup = require("discord-backup"),
client = new Discord.Client(),
settings = {
    prefix: "b!",
    token: ""
};
 
client.on("ready", () => {
    console.log("I'm ready !");
});
 
client.on("message", async message => {
 
    // This reads the first part of your message behind your prefix to see which command you want to use.
    let command = message.content.toLowerCase().slice(settings.prefix.length).split(" ")[0];
 
    // These are the arguments behind the commands.
    let args = message.content.split(" ").slice(1);
 
    // If the message does not start with your prefix return.
    // If the user that types a message is a bot account return.
    // If the command comes from DM return.
    if (!message.content.startsWith(settings.prefix) || message.author.bot || !message.guild) return;
 
    if(command === "create"){
        // Check member permissions
        if(!message.member.hasPermission("ADMINISTRATOR")){
            return message.channel.send(":x: | You must be an administrator of this server to request a backup!");
        }
        // Create the backup
        backup.create(message.guild, {
            jsonBeautify: true
        }).then((backupData) => {
            // And send informations to the backup owner
            message.author.send("The backup has been created! To load it, type this command on the server of your choice: `"+settings.prefix+"load "+backupData.id+"`!");
            message.channel.send(":white_check_mark: Backup successfully created. The backup ID was sent in dm!");
        });
    }
 
    if(command === "load"){
        // Check member permissions
        if(!message.member.hasPermission("ADMINISTRATOR")){
            return message.channel.send(":x: | You must be an administrator of this server to load a backup!");
        }
        let backupID = args[0];
        if(!backupID){
            return message.channel.send(":x: | You must specify a valid backup ID!");
        }
        // Fetching the backup to know if it exists
        backup.fetch(backupID).then(async () => {
            // If the backup exists, request for confirmation
            message.channel.send(":warning: | When the backup is loaded, all the channels, roles, etc. will be replaced! Type `-confirm` to confirm!");
                await message.channel.awaitMessages(m => (m.author.id === message.author.id) && (m.content === "-confirm"), {
                    max: 1,
                    time: 20000,
                    errors: ["time"]
                }).catch((err) => {
                    // if the author of the commands does not confirm the backup loading
                    return message.channel.send(":x: | Time's up! Cancelled backup loading!");
                });
                // When the author of the command has confirmed that he wants to load the backup on his server
                message.author.send(":white_check_mark: | Start loading the backup!");
                // Load the backup
                backup.load(backupID, message.guild).then(() => {
                    // When the backup is loaded, delete them from the server
                    backup.remove(backupID);
                }).catch((err) => {
                    // If an error occurred
                    return message.author.send(":x: | Sorry, an error occurred... Please check that I have administrator permissions!");
				});
        }).catch((err) => {
            // if the backup wasn't found
            return message.channel.send(":x: | No backup found for `"+backupID+"`!");
        });
    }
 
});
 
//Your secret token to log the bot in. (never share this to anyone!)
client.login(settings.token);
```

The bot had the administrators permissions on both servers and its highest role was the highest one of the server. I put your json file in the `node_modules/discord-backup/lib/backups` folder and loaded it.

**Comment by robertcupisz** [comment]
Same issue trying it with your bot and placing the file in that folder.

The only difference that came to mind was that I haven't created any custom roles on this server. Tried that, assigned to the bot and myself, same effect.

Not sure what else might be different.

**Comment by robertcupisz** [comment]
Adding an early out in util.js before both calls to overwritePermissions() fixes things, though:

```
if (finalPermissions.length == 0)
    return [4];

return [4 /*yield*/, category.overwritePermissions({
    // Update category permissions
    permissionOverwrites: finalPermissions
})];
```
```
if (finalPermissions.length == 0)
    return [4];

return [4 /*yield*/, channel.overwritePermissions({
    // Update category permissions
    permissionOverwrites: finalPermissions
})];
```

**Comment by Androz2091** [comment]
I was able to reproduce the problem! I updated my version of Discord.js to the latest one, and there was indeed a problem, now fixed. Try to install version `2.1.13`, it should work.

**Comment by robertcupisz** [comment]
Yeap, latest works! Thank you :)
