### ISSUE TITLE
BitFieldInvalid

### ISSUE THREAD

**Issue by Hosfad** [Androz2091/discord-backup#441]
Hey guys im getting this error when trying to load a backup any ideas ?

```
RangeError [BitFieldInvalid]: Invalid bitfield flag or number: SUPPRESS_GUILD_REMINDER_NOTIFICATIONS.
    at Function.resolve (/home/hosfad/Desktop/discord-backup-api/node_modules/discord.js/src/util/BitField.js:168:11)
    at /home/hosfad/Desktop/discord-backup-api/node_modules/discord.js/src/util/BitField.js:163:54
    at Array.map (<anonymous>)
    at Function.resolve (/home/hosfad/Desktop/discord-backup-api/node_modules/discord.js/src/util/BitField.js:163:40)
    at Guild.edit (/home/hosfad/Desktop/discord-backup-api/node_modules/discord.js/src/structures/Guild.js:797:63)
    at Guild.setSystemChannelFlags (/home/hosfad/Desktop/discord-backup-api/node_modules/discord.js/src/structures/Guild.js:916:17)
    at Object.clearGuild (/home/hosfad/Desktop/discord-backup-api/node_modules/discord-backup/lib/util.js:316:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /home/hosfad/Desktop/discord-backup-api/node_modules/discord-backup/lib/index.js:165:21
[ERROR] 21:02:25 RangeError [BitFieldInvalid]: Invalid bitfield flag or number: SUPPRESS_GUILD_REMINDER_NOTIFICATIONS.
```

**Comment by AlienFreek** [comment]
What version of Discord.js are you using? Use v13 until https://github.com/Androz2091/discord-backup/pull/436 is merged

**Comment by Robbie-Wittenhagen** [comment]
I’m writing a fix for this right now as I already re coded it in typescript
