### ISSUE TITLE
Setting up automatic backups

### ISSUE THREAD

**Issue by dariot99** [Androz2091/discord-backup#46]
Hi, I was trying to set up the bot to do daily automatic backups using the cron tool by npm. I'm struggling into one issue, i'm getting this error:

```
 TypeError: guild.iconURL is not a function
5|index  |     at /root/bot/node_modules/discord-backup/lib/index.js:147:44
5|index  |     at step (/root/bot/node_modules/discord-backup/lib/index.js:33:23)
5|index  |     at Object.next (/root/bot/node_modules/discord-backup/lib/index.js:14:53)
5|index  |     at /root/bot/node_modules/discord-backup/lib/index.js:8:71
5|index  |     at new Promise (<anonymous>)
5|index  |     at __awaiter (/root/bot/node_modules/discord-backup/lib/index.js:4:12)
5|index  |     at /root/bot/node_modules/discord-backup/lib/index.js:119:83
5|index  |     at new Promise (<anonymous>)
5|index  |     at /root/bot/node_modules/discord-backup/lib/index.js:119:35
5|index  |     at step (/root/bot/node_modules/discord-backup/lib/index.js:33:23)
```

Consider that the bot is working fine if I use it with the original code and I have the latest updates for discord.js, npm and such, so I think I messed up while coding the automatic backup part, can anyone give me an help or advice?
This is the code:

```
client.on("ready", () => {
    console.log("I'm ready !");
    
        const channel = client.channels.cache.get('669955470823260190');
        const CronJob = require('cron').CronJob;
        
let autobackup = new CronJob ("00 15 17 * * *", function() {
console.log("Backupping now!");
channel.send('Daily Backup starting now.');
   backup.create({
            jsonBeautify: true
        })
        }, null, true, 'Europe/Rome');
    autobackup.start();
    
});
```

**Comment by Androz2091** [comment]
Hello,
This is because you are using Discord.js v11. To fix your issue, you will have to update it to v12:
```sh
npm install discord.js@12.2.0
```

**Comment by dariot99** [comment]
Hi @Androz2091 thanks for your fast reply. Unfortunally I'm using Discord.js v12 already, actually I just updated it to 12.2.0 as I was running the 12.1.0 version before, but nothing changed.

**Comment by Androz2091** [comment]
Oh, I see. You need to replace:
```js
 backup.create({
    jsonBeautify: true
 })
```
with:
```js
 backup.create(channel.guild, {
    jsonBeautify: true
 })
```
It will create a backup for the guild of channel you are getting here:
```js
const channel = client.channels.cache.get('669955470823260190');
```

**Comment by dariot99** [comment]
Looks like it's working fine now, thanks once again @Androz2091 !
Solved.
