### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by GlamgarOnDiscord** [Androz2091/discord-backup#524]
Hello, when i try to load :

TypeError: Cannot read properties of undefined (reading 'cache')
    at x (/home/runner/backup/node_modules/@outwalk/discord-backup/dist/index.js:1:4228)
    at Object.Y [as load] (/home/runner/backup/node_modules/@outwalk/discord-backup/dist/index.js:3:144)

**Comment by GlamgarOnDiscord** [comment]
Code :

`
const guildId = '1144349513121792101'  
const backupData = await backup.fetch(backupID);
    // Options de chargement de la sauvegarde
    const loadOptions = {
      clearGuildBeforeRestore: true,
      maxMessagesPerChannel: 10,
      speed: 250,
    };

    // Chargez la sauvegarde sur le serveur Discord spécifié avec les options
    await backup.load(backupData, guildId, loadOptions);
    `

**Comment by sw3do** [comment]
Can you tell me the version of discord.js?
