### ISSUE TITLE
This error i get

### ISSUE THREAD

**Issue by B3ni15** [Androz2091/discord-backup#525]
Hiba történt a backup létrehozása közben: TypeError: guild.fetchBans is not a function
    at Object.<anonymous> (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord-backup\lib\create.js:54:48)
    at step (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord-backup\lib\create.js:33:23)
    at Object.next (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord-backup\lib\create.js:14:53)
    at C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord-backup\lib\create.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord-backup\lib\create.js:4:12)
    at Object.getBans (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord-backup\lib\create.js:48:12)
    at C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord-backup\lib\index.js:183:67
    at step (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord-backup\lib\index.js:33:23)
    at Object.next (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord-backup\lib\index.js:14:53)
    at fulfilled (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord-backup\lib\index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by B3ni15** [comment]
I got another error:

2023-10-26 19:47:40 [info] [ERROR] [unhandledRejection] Invalid Form Body
name: Could not interpret "{'name': '「❗」státusz', 'type': 2, 'parent': None}" as string.
DiscordAPIError: Invalid Form Body
name: Could not interpret "{'name': '「❗」státusz', 'type': 2, 'parent': None}" as string.
    at RequestHandler.execute (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async GuildChannelManager.create (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\managers\GuildChannelManager.js:176:18) {
  method: 'post',
  path: '/guilds/847852505252495442/channels',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: {
      name: [Object],
      topic: undefined,
      type: 0,
      nsfw: undefined,
      bitrate: undefined,
      user_limit: undefined,
      parent_id: undefined,
      position: undefined,
      permission_overwrites: undefined,
      rate_limit_per_user: undefined,
      rtc_region: undefined,
      video_quality_mode: undefined,
      available_tags: undefined,
      default_reaction_emoji: undefined,
      default_sort_order: undefined,
      default_forum_layout: undefined
    },
    files: []
  }
} Promise {
  <rejected> DiscordAPIError: Invalid Form Body
  name: Could not interpret "{'name': '「❗」státusz', 'type': 2, 'parent': None}" as string.
      at RequestHandler.execute (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async RequestHandler.push (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
      at async GuildChannelManager.create (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\managers\GuildChannelManager.js:176:18) {
    method: 'post',
    path: '/guilds/847852505252495442/channels',
    code: 50035,
    httpStatus: 400,
    requestData: { json: [Object], files: [] }
  }
}
2023-10-26 19:47:41 [info] [ERROR] [unhandledRejection] Invalid Form Body
name: Could not interpret "{'name': '--Információk--', 'type': 2, 'parent': None}" as string.
DiscordAPIError: Invalid Form Body
name: Could not interpret "{'name': '--Információk--', 'type': 2, 'parent': None}" as string.
    at RequestHandler.execute (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async GuildChannelManager.create (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\managers\GuildChannelManager.js:176:18) {
  method: 'post',
  path: '/guilds/847852505252495442/channels',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: {
      name: [Object],
      topic: undefined,
      type: 0,
      nsfw: undefined,
      bitrate: undefined,
      user_limit: undefined,
      parent_id: undefined,
      position: undefined,
      permission_overwrites: undefined,
      rate_limit_per_user: undefined,
      rtc_region: undefined,
      video_quality_mode: undefined,
      available_tags: undefined,
      default_reaction_emoji: undefined,
      default_sort_order: undefined,
      default_forum_layout: undefined
    },
    files: []
  }
} Promise {
  <rejected> DiscordAPIError: Invalid Form Body
  name: Could not interpret "{'name': '--Információk--', 'type': 2, 'parent': None}" as string.
      at RequestHandler.execute (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async RequestHandler.push (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
      at async GuildChannelManager.create (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\managers\GuildChannelManager.js:176:18) {
    method: 'post',
    path: '/guilds/847852505252495442/channels',
    code: 50035,
    httpStatus: 400,
    requestData: { json: [Object], files: [] }
  }
}
2023-10-26 19:47:41 [info] [ERROR] [unhandledRejection] Invalid Form Body
name: Could not interpret "{'name': '---Staff---', 'type': 2, 'parent': None}" as string.
DiscordAPIError: Invalid Form Body
name: Could not interpret "{'name': '---Staff---', 'type': 2, 'parent': None}" as string.
    at RequestHandler.execute (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async GuildChannelManager.create (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\managers\GuildChannelManager.js:176:18) {
  method: 'post',
  path: '/guilds/847852505252495442/channels',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: {
      name: [Object],
      topic: undefined,
      type: 0,
      nsfw: undefined,
      bitrate: undefined,
      user_limit: undefined,
      parent_id: undefined,
      position: undefined,
      permission_overwrites: undefined,
      rate_limit_per_user: undefined,
      rtc_region: undefined,
      video_quality_mode: undefined,
      available_tags: undefined,
      default_reaction_emoji: undefined,
      default_sort_order: undefined,
      default_forum_layout: undefined
    },
    files: []
  }
} Promise {
  <rejected> DiscordAPIError: Invalid Form Body
  name: Could not interpret "{'name': '---Staff---', 'type': 2, 'parent': None}" as string.
      at RequestHandler.execute (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async RequestHandler.push (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
      at async GuildChannelManager.create (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\managers\GuildChannelManager.js:176:18) {
    method: 'post',
    path: '/guilds/847852505252495442/channels',
    code: 50035,
    httpStatus: 400,
    requestData: { json: [Object], files: [] }
  }
}
2023-10-26 19:47:41 [info] [ERROR] [unhandledRejection] Invalid Form Body
name: Could not interpret "{'name': '「💲」prémium', 'type': 2, 'parent': None}" as string.
DiscordAPIError: Invalid Form Body
name: Could not interpret "{'name': '「💲」prémium', 'type': 2, 'parent': None}" as string.
    at RequestHandler.execute (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async GuildChannelManager.create (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\managers\GuildChannelManager.js:176:18) {
  method: 'post',
  path: '/guilds/847852505252495442/channels',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: {
      name: [Object],
      topic: undefined,
      type: 0,
      nsfw: undefined,
      bitrate: undefined,
      user_limit: undefined,
      parent_id: undefined,
      position: undefined,
      permission_overwrites: undefined,
      rate_limit_per_user: undefined,
      rtc_region: undefined,
      video_quality_mode: undefined,
      available_tags: undefined,
      default_reaction_emoji: undefined,
      default_sort_order: undefined,
      default_forum_layout: undefined
    },
    files: []
  }
} Promise {
  <rejected> DiscordAPIError: Invalid Form Body
  name: Could not interpret "{'name': '「💲」prémium', 'type': 2, 'parent': None}" as string.
      at RequestHandler.execute (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async RequestHandler.push (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
      at async GuildChannelManager.create (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\managers\GuildChannelManager.js:176:18) {
    method: 'post',
    path: '/guilds/847852505252495442/channels',
    code: 50035,
    httpStatus: 400,
    requestData: { json: [Object], files: [] }
  }
}
2023-10-26 19:47:41 [info] [ERROR] [unhandledRejection] Invalid Form Body
name: Could not interpret "{'name': '---Logs---', 'type': 2, 'parent': None}" as string.
DiscordAPIError: Invalid Form Body
name: Could not interpret "{'name': '---Logs---', 'type': 2, 'parent': None}" as string.
    at RequestHandler.execute (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async GuildChannelManager.create (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\managers\GuildChannelManager.js:176:18) {
  method: 'post',
  path: '/guilds/847852505252495442/channels',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: {
      name: [Object],
      topic: undefined,
      type: 0,
      nsfw: undefined,
      bitrate: undefined,
      user_limit: undefined,
      parent_id: undefined,
      position: undefined,
      permission_overwrites: undefined,
      rate_limit_per_user: undefined,
      rtc_region: undefined,
      video_quality_mode: undefined,
      available_tags: undefined,
      default_reaction_emoji: undefined,
      default_sort_order: undefined,
      default_forum_layout: undefined
    },
    files: []
  }
} Promise {
  <rejected> DiscordAPIError: Invalid Form Body
  name: Could not interpret "{'name': '---Logs---', 'type': 2, 'parent': None}" as string.
      at RequestHandler.execute (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async RequestHandler.push (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
      at async GuildChannelManager.create (C:\Users\Beni\OneDrive\bot\HunTools-bot\node_modules\discord.js\src\managers\GuildChannelManager.js:176:18) {
    method: 'post',
    path: '/guilds/847852505252495442/channels',
    code: 50035,
    httpStatus: 400,
    requestData: { json: [Object], files: [] }
  }
}

**Comment by B3ni15** [comment]
![image](https://github.com/Androz2091/discord-backup/assets/90302291/519a41ce-814b-4b31-bdd2-99559151f21c)

**Comment by aguskolod** [comment]
Ive got the same error, could you get it to work?

**Comment by B3ni15** [comment]
Nah.. Its doesn't work either.
