### ISSUE TITLE
Backup not found while a backup existing.

### ISSUE THREAD

**Issue by MrAugu** [Androz2091/discord-backup#6]
After some troubleshooting.. i figured out that problem was in `functions/utils.js:76:84`
Error was miss-thrown by the promise at line 150 in `index.js`.

Original error stack:
```
TypeError: Cannot read property 'id' of undefined
 at guild.roles.filter (/home/mraugu/ftp/bots/f-u/node_modules/discord-backup/functions/utils.js:76:84)
 at Map.filter (/home/mraugu/ftp/bots/f-u/node_modules/discord.js/src/util/Collection.js:227:11)
 at Object.clearGuild (/home/mraugu/ftp/bots/f-u/node_modules/discord-backup/functions/utils.js:76:17)
 at getBackupInformations.then (/home/mraugu/ftp/bots/f-u/node_modules/discord-backup/index.js:164:29)
```

It was fixed by fixing the filtering condition on the line 76.
```js
// Old:
guild.roles.filter((role) => role.editable && role.id !== guild.roles.everyone.id).forEach((role) => {
  role.delete().catch((err) => {});
});
// New:
guild.roles.filter((role) => role.managed === false  && role.id !== guild.id && role.editable).forEach((role) => {
  role.delete().catch((err) => {});
});

**Comment by Androz2091** [comment]
Yeah you're right
Would you like to open a PR to fix this?
