### ISSUE TITLE
I have a problem for create a backup

### ISSUE THREAD

**Issue by Azkun** [Androz2091/discord-backup#7]
My code is :
```js
if(args[0] === "create"){
   if(!message.member.hasPermission("ADMINISTRATOR")){
            return message.channel.send(":x: | Tu dois être un administrateur pour éxécuter cette commande !");
        }
 
        backup.create(message.guild).then((backupID) => {
          
            message.author.send("La backup a été crée, tu peux la load en faisant "+prefix+"load "+backupID+"`!");
        }).catch(() => {
          message.channel.send('Une erreur est survenue, merci de report ce bug à Azkun#9867')
        });
    }
```
This code return `  message.channel.send('Une erreur est survenue, merci de report ce bug à Azkun#9867')`, this is for message.guild ? Or a another error ?

**Comment by Azkun** [comment]
>  *The discord server you want to backup*

What ? serverid, servername... ?

**Comment by Androz2091** [comment]
The Discord server object, so `message.guild`. It should works

**Comment by Azkun** [comment]
> You must install and use discord.js version 12 or higher to use this package!

Thank's for help Androz !

**Comment by Azkun** [comment]
Hmm, discord.js no have  12 version 🤔 What ?

**Comment by Androz2091** [comment]
You can install discord.js v12 with `npm install discordjs/discord.js`

**Comment by Azkun** [comment]
What,
```
/rbd/pnpm-volume/169a06d7-675d-4164-bfe0-b8417a09c977/node_modules/.github.com/discordjs/discord.js/d05334fd3cd8fb913e869654f25eb8230493de11/node_modules/discord.js/src/structures/interfaces/Collector.js:203
  async *[Symbol.asyncIterator]() {
        ^
SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/rbd/pnpm-volume/169a06d7-675d-4164-bfe0-b8417a09c977/node_modules/.github.com/discordjs/discord.js/d05334fd3cd8fb913e869654f25eb8230493de11/node_modules/discord.js/src/structures/MessageCollector.js:3:19)
```

**Comment by Azkun** [comment]
I use Glitch.com, this is the problem ?

**Comment by Androz2091** [comment]
Your version of nodejs is not compatible with discord.js v12
And I don't think that you change it with Glitch

**Comment by Azkun** [comment]
What's the good version? I can install a new NodeJs on Glitch.

**Comment by Androz2091** [comment]
Nodejs v12 or higher
