### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by qutziscoding** [Androz2091/discord-backup#77]
Im using atlanta master branch.
```py
TypeError: Cannot read property 'filter' of undefined
    at Object.<anonymous> (Z:\Coding\Zeka Discord Bot\node_modules\discord-backup\lib\master\create.js:79:18)
    at step (Z:\Coding\Zeka Discord Bot\node_modules\discord-backup\lib\master\create.js:33:23)
    at Object.next (Z:\Coding\Zeka Discord Bot\node_modules\discord-backup\lib\master\create.js:14:53)
    at Z:\Coding\Zeka Discord Bot\node_modules\discord-backup\lib\master\create.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (Z:\Coding\Zeka Discord Bot\node_modules\discord-backup\lib\master\create.js:4:12)
    at Object.getRoles (Z:\Coding\Zeka Discord Bot\node_modules\discord-backup\lib\master\create.js:74:12)
    at Z:\Coding\Zeka Discord Bot\node_modules\discord-backup\lib\index.js:192:67
    at step (Z:\Coding\Zeka Discord Bot\node_modules\discord-backup\lib\index.js:33:23)
    at Object.next (Z:\Coding\Zeka Discord Bot\node_modules\discord-backup\lib\index.js:14:53)
    at fulfilled (Z:\Coding\Zeka Discord Bot\node_modules\discord-backup\lib\index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by Androz2091** [comment]
Please open an issue [here](https://github.com/Androz2091/AtlantaBot) instead.
